"""add test records table

Revision ID: be8440705f4b
Revises: 4e7b2202c8c7
Create Date: 2025-06-15 16:21:56.961208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be8440705f4b'
down_revision = '4e7b2202c8c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('model_id', sa.Integer(), nullable=False),
        sa.Column('template_id', sa.Integer(), nullable=True),
        sa.Column('prompt', sa.Text(), nullable=False),
        sa.Column('variables', sa.JSON(), nullable=True, server_default='{}'),
        sa.Column('response', sa.Text(), nullable=False),
        sa.Column('evaluation', sa.JSON(), nullable=True, server_default='{}'),
        sa.Column('is_deleted', sa.Boolean(), server_default='0'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)')),
        sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.text('(CURRENT_TIMESTAMP)')),
        sa.ForeignKeyConstraint(['model_id'], ['llm_models.id'], ),
        sa.ForeignKeyConstraint(['template_id'], ['prompt_templates.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_records_id'), 'test_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_records_id'), table_name='test_records')
    op.drop_table('test_records')
    # ### end Alembic commands ### 